- modules/aws/main.tf
Reverts streamnative/terraform-managed-cloud#10
For AWS managed IAM policies, their ARN should not include account id. TIL
> Revert "Fix account id in arn"

- modules/aws/files/bootstrap_role_iam_policy.json.tpl
The iam action for EKS is not DeleteNodeGroup but DeleteNodegroup
In order to just remove this, instead just convert this to a wildcard
> Fix bad case for DeleteNodeGroup

- modules/aws/README.md
- modules/aws/files/bootstrap_role_iam_policy.json.tpl
- modules/aws/main.tf
- modules/aws/variables.tf
This fixes an issue not only with the case but also the overly restrictive nodepool pattern. Instead, we just use the cluster_pattern in the arn, as that is sufficient to limit us to only manage nodepools in clusters managed by SN
> Fix restrictive nodepool pattern

- modules/aws/files/bootstrap_role_iam_policy.json.tpl
- modules/aws/files/permission_boundary_iam_policy.json.tpl
The [terraform-aws-cloud](https://github.com/streamnative/terraform-aws-cloud/blob/0e400642f61318d36f6a3c9de8b1c7a225fc3470/aws_load_balancer_controller.tf#L266) requires iam:CreatePolicy permission to create IAM Policy.
> fix: add iam:CreatePolicy

- modules/aws/files/bootstrap_role_iam_policy.json.tpl
- modules/aws/files/management_role_iam_policy.json.tpl
- modules/aws/files/runtime_iam_policy.json.tpl
- modules/aws/variables.tf
This commit updates the runtime policy to support more consistent support of snapshot creation for the purposes of backups.
Additionally, it adds some additional call to aid in debugging.
This also bumps the version to prepare for a release
> Update policy versions and prepare for release

- modules/aws/files/runtime_iam_policy.json.tpl
- modules/aws/variables.tf
In #21, the policy was updated to fix snapshots, but erroneously, an extra deny was added for CreateVolume
This fixes that and bumps the version
> Don't deny createVolume

- modules/aws/main.tf
This commit whitelists a few more roles and simplifies the role list to be a wildcard
Rather than explictily list each EKS role, we instead use a wildcard.
This grants us access to use Fargate role (otherwise we already had listed each role) and then also adds SSM which we can use in the future
> Whitelist more roles we can attach

- modules/aws/main.tf
- modules/aws/variables.tf
In order to finer grained permissions to customer environments, access via services and access via SN support engineers in being seperated.
For most customers, this will be a simple update of the role, for customers that require more specific access restrictions, a list of roles will be provided
Additionally, a small feature allow for principal ids to be checked is added, which is used in special cases
Finally, for testing, this adding a test suffix to make it easy to run multiple versions and bumps the version in prep of deploy
> Update roles to support separate access for users vs services

- modules/aws/files/aws_lb_controller_iam_policy.json.tpl
Ref: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692#issuecomment-1602615427
Diff:
```bash
diff <(sed 's/${partition}/aws/' terraform-managed-cloud/modules/aws/files/aws_lb_controller_iam_policy.json.tpl) iam_policy.json
74,79c74
<             "Resource": "*",
<             "Condition": {
<                 "StringEquals": {
<                     "aws:ResourceTag/Vendor": "StreamNative"
<                  }
<             }
---
>             "Resource": "*"
128,131c123
<                 },
<                 "StringEquals": {
<                     "aws:ResourceTag/Vendor": "StreamNative"
<                  }
---
>                 }
```
> Fix aws lb iam policy

- modules/aws/files/bootstrap_role_iam_policy.json.tpl
For using old existing data volumes, to rebuild or migrate.
> feat: add ec2:AttachVolume to bootstrap policy

- .gitignore
- examples/gcp/private-service/main.tf
- modules/gcp/private-service/common.tf
- modules/gcp/private-service/main.tf
```hcl
module "gcp-private-service-shared" {
source = "github.com/streamnative/terraform-managed-cloud//modules/gcp/private-service?ref=v3.5.0"
region              = "us-east1"
project             = "<service-project>"
network_project     = "<network-project>"
network_name        = "shared"
subnet_name         = "shared"
domain_name         = "gcp-use1-prod-snc.o-xxxx.g.snio.cloud"
service_attachment  = "projects/<pulsar-project-name>/regions/us-east1/serviceAttachments/pulsar-private-service"
cross_region_access = false
suffix              = "shared"
}
```
> feat: Support create private service endpoint on shared VPC

- modules/aws/files/bootstrap_role_iam_policy.json.tpl
- modules/aws/variables.tf
Note: Remove the condition check for the `Vendor` tag for `AcceptVpcPeering` action, as the accepter PeeringConnection created by AWS automatically won't have any tags.
> feat: add iam policy for aws vpc peering

- .github/workflows/pr.yaml
The PR #38 miss-deleted the pr check ci workflow, we need add it back.
> fix: add pr check ci

- modules/aws/main.tf
Maximum session duration (in seconds) that you want to set for the specified role. If you do not specify a value for this setting, the default maximum of one hour is applied. This setting can have a value from 1 hour to 12 hours.
The default 1 hour is too short for debugging customer's issues.
Ref: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role#max_session_duration
> feat: update aws role session duration

- modules/aws/files/management_role_iam_policy.json.tpl
- modules/aws/files/permission_boundary_iam_policy.json.tpl
Grant manager role `iam:PutRolePolicy` and `iam:DeleteRolePolicy` for configuring bucket read/write permission for broker
> feat: Allow iam:PutRolePolicy and iam:DeleteRolePolicy in aws

- modules/aws/files/bootstrap_role_iam_policy.json.tpl
To support https://github.com/streamnative/terraform-aws-cloud/pull/125
When apply with optimized route tables, we need `ec2:ReplaceRoute` and `ec2:ReplaceRouteTableAssociation` permission
- Add `ec2:ReplaceRoute` and `ec2:ReplaceRouteTableAssociation` to bootstrap role
> feat(aws): allow update route tables

- modules/aws/files/bootstrap_role_iam_policy.json.tpl
The actual generated ASG tag key is `eks:cluster-name` rather than `cluster-name`.
Wrong condition will block autoscaling tagging operations.
The AWS didn't explicitly tell user about this, but here are some references:
- https://docs.aws.amazon.com/eks/latest/userguide/eks-using-tags.html
- https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group
- Change condition key to `"autoscaling:ResourceTag/eks:cluster-name"`
> fix(aws): autoscaling condition key

- modules/gcp/vendor-access/README.md
- modules/gcp/vendor-access/common.tf
- modules/gcp/vendor-access/docs/main.tf
- modules/gcp/vendor-access/main.tf
Introduce new parameter `streamnative_org_id` which is required to grant permissions of GCP project for impersonation
> feat: Support GCP impersonation

- modules/aws/vendor-access/files/provision2.json.tpl
Karpenter need manage the instance profile directly rather than managed node groups.
The role is managed here: https://github.com/streamnative/terraform-aws-cloud/blob/master/main.tf#L435
> fix: allow detach instance profile

- examples/gcp/private-service/main.tf
- modules/gcp/private-service/common.tf
- modules/gcp/private-service/main.tf
Usage example
```hcl
module "topology_aware_psc" {
source = "git::https://github.com/streamnative/terraform-managed-cloud//modules/gcp/private-service?ref=main"
domain_name  = "gcp-usc1-example.example.com"
project      = "<your-client-gcp-project>"
region       = "us-central1"
network_name = "<your-client-network>"
subnet_name  = "<your-client-subnet>"
suffix       = "gcp-usc1-example"
service_attachments = [
{
zone = "us-central1-a",
id   = "projects/<pulsar-project>/regions/us-central1/serviceAttachments/istio-system-istio-ingressgateway-us-central1-a",
},
{
zone = "us-central1-b",
id   = "projects/<pulsar-project>/regions/us-central1/serviceAttachments/istio-system-istio-ingressgateway-us-central1-b",
},
{
zone = "us-central1-c",
id   = …
```
> feat: Support creating separate PSC for each zone in GCP

- modules/alicloud/private-link/README.md
> docs: Improve alicloud privatelink docs
